name: ecommerce_store
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  readmore: ^2.2.0
  dartz: ^0.10.1
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.21
  image_picker: ^1.0.5
  animations: ^2.0.8
  lottie: ^2.6.0
  flutter_animate: ^4.4.0
  http: ^1.2.0
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/icon/
    - assets/image/

  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Thin.ttf
          weight: 100
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Light.ttf
          weight: 300
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/sf-pro-display/SF-Pro-Display-Black.ttf
          weight: 900
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sf-pro/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/fonts/sf-pro/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/fonts/sf-pro/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/fonts/sf-pro/sf-pro-text-bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
