// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Q0CZN2QdieVMHKcXYsqmRii7sqj-WRc',
    appId: '1:1095584126050:web:e6b334bca9830001066d3b',
    messagingSenderId: '1095584126050',
    projectId: 'ecommerce-store-2002c',
    authDomain: 'ecommerce-store-2002c.firebaseapp.com',
    storageBucket: 'ecommerce-store-2002c.appspot.com',
    measurementId: 'G-P5DVDTK7VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91UkDBMksvx_HGVy5ybrDYnpiZ9qwCRg',
    appId: '1:1095584126050:android:f2225f2cf5fb0209066d3b',
    messagingSenderId: '1095584126050',
    projectId: 'ecommerce-store-2002c',
    storageBucket: 'ecommerce-store-2002c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTESvPVq1caSe5SI-rETr1Ww8g-Kajbus',
    appId: '1:1095584126050:ios:8d9eaa3a1a133d66066d3b',
    messagingSenderId: '1095584126050',
    projectId: 'ecommerce-store-2002c',
    storageBucket: 'ecommerce-store-2002c.appspot.com',
    iosBundleId: 'com.example.ecommerceStore',
  );
}
